import { NavigationSection } from './types';

export const navigationSections: NavigationSection[] = [
  {
    id: 'overview',
    title: 'Översiktsblad',
    description: 'Overview and introduction to the onboarding process',
    component: 'Overview',
    completed: false,
  },
  {
    id: 'migration',
    title: '1. Migrering',
    description: 'Migration data and requirements',
    component: 'Migration',
    completed: false,
  },
  {
    id: 'email-addresses',
    title: '2. E-postadress',
    description: 'Email addresses and associated groups',
    component: 'EmailAddresses',
    completed: false,
  },
  {
    id: 'working-hours',
    title: '3. Arbetstid',
    description: 'Business hours configuration',
    component: 'WorkingHours',
    completed: false,
  },
  {
    id: 'agents-groups',
    title: '4. Agenter & Grupper',
    description: 'Agents and groups management',
    component: 'AgentsGroups',
    completed: false,
  },
  {
    id: 'sla',
    title: '5. SLA',
    description: 'Service Level Agreements configuration',
    component: 'SLA',
    completed: false,
  },
  {
    id: 'contact-fields',
    title: '6. Kontaktfält',
    description: 'Contact field definitions',
    component: 'ContactFields',
    completed: false,
  },
  {
    id: 'ticket-fields',
    title: '7. Ärendefält',
    description: 'Ticket field definitions',
    component: 'TicketFields',
    completed: false,
  },
  {
    id: 'ticket-forms',
    title: '8. Ärendeformulär',
    description: 'Ticket form builder',
    component: 'TicketForms',
    completed: false,
  },
  {
    id: 'predefined-forms',
    title: '9. Fördefinierade formulär',
    description: 'Predefined form templates',
    component: 'PredefinedForms',
    completed: false,
  },
  {
    id: 'canned-responses',
    title: '10. Fördefinerade svarsmallar',
    description: 'Canned response templates',
    component: 'CannedResponses',
    completed: false,
  },
  {
    id: 'solution-articles',
    title: '11. Lösningsartiklar',
    description: 'Knowledge base articles',
    component: 'SolutionArticles',
    completed: false,
  },
  {
    id: 'automations',
    title: '12. Automatiseringar',
    description: 'Automation rules and workflows',
    component: 'Automations',
    completed: false,
  },
  {
    id: 'csat',
    title: '13. CSAT (Freshchat)',
    description: 'Customer satisfaction survey configuration',
    component: 'CSAT',
    completed: false,
  },
  {
    id: 'portal-settings',
    title: '14. Portalinställningar',
    description: 'Portal configuration settings',
    component: 'PortalSettings',
    completed: false,
  },
  {
    id: 'integrations',
    title: '15. Integrationer',
    description: 'Third-party integrations',
    component: 'Integrations',
    completed: false,
  },
  {
    id: 'reports',
    title: '16. Rapporter',
    description: 'Custom reports configuration',
    component: 'Reports',
    completed: false,
  },
  {
    id: 'review-submit',
    title: 'Review & Submit',
    description: 'Final review and submission',
    component: 'ReviewSubmit',
    completed: false,
  },
];
